# FROM node:12-buster
FROM jboss/wildfly
ADD node-info.war /opt/jboss/wildfly/standalone/deployments/

# Enable health and metrics support
# ENV KC_HEALTH_ENABLED=true
# ENV KC_METRICS_ENABLED=true

# Configure a database vendor
# ENV KC_DB=postgres

# Set the working directory to /opt/keycloak inside the container
WORKDIR /opt/keycloak

# Copy app files
COPY . .

# ==== BUILD =====
RUN apt-get update -y
# RUN apt-get install -y lsof

RUN chmod g=u /etc/passwd \
  && chmod -R g=u /opt/keycloak \
  && chgrp -R 0 /opt/keycloak \
  && chmod +x /bin/entrypoint.sh \
  && chmod a+rwx /bin/standalone.sh

# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/standalone.sh build

# ==== RUN =======
# Set the env to "production"
# ENV NODE_ENV production

# change these values to point to a running postgres instance
# ENV KC_DB_URL=<DBURL>
# ENV KC_DB_USERNAME=<DBUSERNAME>
# ENV KC_DB_PASSWORD=<DBPASSWORD>
# ENV KC_HOSTNAME=localhost
# ENTRYPOINT [ "/bin/entrypoint.sh" ]
ENTRYPOINT ["/opt/keycloak/bin/standalone.sh"]
USER 105001


# REFERENCE: WildFly Dockerfile
# FROM jboss/wildfly
# RUN /opt/jboss/wildfly/bin/add-user.sh admin welcome1 --silent
# CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]